### ISSUE TITLE
COYO-700M Dataset Download Script Error

### ISSUE THREAD

**Issue by XuGW-Kevin** [NVlabs/VILA#107]
Hi, thanks for your wonderful work and generous sharing!
When I tried to download COYO-700M Dataset according to the instructions in [data_prepare file](https://github.com/NVlabs/VILA/tree/main/data_prepare)  , I got the following error when I tried to run `python coyo_downloader.py $SHARD`:

```python
Traceback (most recent call last):
  File "***/playground/data/coyo-700m/coyo_downloader.py", line 122, in <module>
    asyncio.run(main(metadata_list))
  File "***/miniconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "***/miniconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "***/playground/data/coyo-700m/coyo_downloader.py", line 113, in main
    await asyncio.gather(*tasks)
  File "***/playground/data/coyo-700m/coyo_downloader.py", line 51, in download_file
    async with semaphore:  # limit the number of simultaneous downloads
  File "***/miniconda3/lib/python3.9/asyncio/locks.py", line 14, in __aenter__
    await self.acquire()
  File "***/miniconda3/lib/python3.9/asyncio/locks.py", line 417, in acquire
    await fut
RuntimeError: Task <Task pending name='Task-14' coro=<download_file() running at ***/playground/data/coyo-700m/coyo_downloader.py:51> cb=[_gather.<locals>._done_callback() at ***/miniconda3/lib/python3.9/asyncio/tasks.py:767]> got Future <Future pending> attached to a different loop
```

Does anyone encounter similar issues? Thanks a lot!

**Comment by Lyken17** [comment]
This is usually caused too frequent download requests.

**Comment by XuGW-Kevin** [comment]
Thanks! For those who still have trouble using the downloading file, I suggest directly using `requests` library.

**Comment by Lyken17** [comment]
awsome you find the workaround! Would you like to draft PR to the repo to fix the issue? @XuGW-Kevin
