### ISSUE TITLE
AWQ Tinychat tensor mismatch RuntimeError

### ISSUE THREAD

**Issue by leon-seidel** [NVlabs/VILA#16]
Hi everyone,

When running VILA with Tinychat I get the following error, across different transformers, torch and CUDA versions. Tinychat works well with LlaMA and LLaVA for me, so the problem might be on the VILA side. Running the FP16 VILA models within this repo works just fine. Any ideas on this?

`ASSISTANT: Traceback (most recent call last):
  File "/opt/llm-awq/tinychat/vlm_demo.py", line 233, in <module>
    main(args)
  File "/opt/llm-awq/tinychat/vlm_demo.py", line 179, in main
    outputs = stream_output(output_stream, time_stats)
  File "/opt/llm-awq/tinychat/utils/conversation_utils.py", line 83, in stream_output
    for outputs in output_stream:
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/opt/llm-awq/tinychat/stream_generators/llava_stream_gen.py", line 177, in LlavaStreamGenerator
    out = model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/llm-awq/tinychat/models/llava_llama.py", line 261, in forward
    out = super().forward(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/llm-awq/tinychat/models/llama.py", line 318, in forward
    h = self.model(tokens, start_pos, inputs_embeds)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/llm-awq/tinychat/models/llama.py", line 302, in forward
    h = layer(h, start_pos, freqs_cis, mask)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/llm-awq/tinychat/models/llama.py", line 257, in forward
    h = x + self.self_attn.forward(
  File "/opt/llm-awq/tinychat/modules/fused_attn.py", line 259, in forward
    self.cache_v[:bsz, :, start_pos : start_pos + seqlen, :] = values_store
RuntimeError: The expanded size of the tensor (2048) must match the existing size (2353) at non-singleton dimension 2.  Target sizes: [1, 32, 2048, 128].  Tensor sizes: [32, 2353, 128]
`

**Comment by kentang-mit** [comment]
Hi @leon-seidel,

Sorry for the delayed response. You may want to modify the `max_seq_len` [here](https://github.com/mit-han-lab/llm-awq/blob/main/tinychat/utils/constants.py#L6) to a larger value. 

Best,
Haotian
