### ISSUE TITLE
unexpected keyword argument 'seqlens_in_batch'

### ISSUE THREAD

**Issue by katopz** [NVlabs/VILA#19]
I try

```bash
!python3 -W ignore llava/eval/run_llava.py \
    --model-path Efficient-Large-Model/VILA-7B \
    --conv-mode vicuna_v1 \
    --query "<image>\n Please describe the traffic condition." \
    --image-file "demo_images/av.png"
```

But got an error.
```bash
Traceback (most recent call last):
  File "/home/katopz/book/examples/ml/infer/VILA/llava/eval/run_llava.py", line 160, in <module>
    eval_model(args)
  File "/home/katopz/book/examples/ml/infer/VILA/llava/eval/run_llava.py", line 118, in eval_model
    output_ids = model.generate(
  File "/home/katopz/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/katopz/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1764, in generate
    return self.sample(
  File "/home/katopz/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2861, in sample
    outputs = self(
  File "/home/katopz/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/katopz/book/examples/ml/infer/VILA/llava/model/language_model/llava_llama.py", line 125, in forward
    outputs = super().forward(
TypeError: LlamaForCausalLM.forward() got an unexpected keyword argument 'seqlens_in_batch'
```

FYI: `trsnsformer=4.36.2`

Not sure what I miss, Thanks

**Comment by hzhang57** [comment]
#10 sovled this

**Comment by Lyken17** [comment]
you need to follow full setup instructions

```
cp -rv ./llava/train/transformers_replace/* ~/anaconda3/envs/vila/lib/python3.10/site-packages/transformers/models/
```

**Comment by katopz** [comment]
I do follow full setup instructions but I'm on WSL2 and it seem like I have to use `miniconda` and I needed to

```bash
## change to miniconda3
~/miniconda3/condabin/conda create -n vila python=3.10 -y
~/miniconda3/condabin/conda activate vila

pip install --upgrade pip  # enable PEP 660 support
wget https://github.com/Dao-AILab/flash-attention/releases/download/v2.4.2/flash_attn-2.4.2+cu118torch2.0cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
pip install flash_attn-2.4.2+cu118torch2.0cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
pip install -e .
pip install -e ".[train]"

pip install git+https://github.com/huggingface/transformers@v4.36.2

## also here
cp -r ./llava/train/transformers_replace/* ~/miniconda3/envs/vila/lib/python3.10/site-packages/transformers/models/

## but somehow notebook via VSCode still point to `~/.local` so I do copy to this instead
cp -r ./llava/train/transformers_replace/* ~/.local/lib/python3.10/site-packages/transformers/models/
```

and then restart and select `villa` kernel environment via VSCode and now it work.
And yes I'm pretty much confuse about environment (pretty much mess up).

Anyway it working now after copy it to everywhere (anaconda newbies here and everything confuse me a lot).

Thanks
