### ISSUE TITLE
LoRA for downstream task tuning

### ISSUE THREAD

**Issue by hzhang57** [NVlabs/VILA#2]
Hi, Lyken17 , thank you for sharing wonderful works, 
I would like to customize the VILA for downstream task tuning and find the LoRA args in https://github.com/Efficient-Large-Model/VILA/blob/90eda3dc4a9fad021a7adae59cd1a3f8bce78b23/llava/train/args.py#L75
Can I use lora by adding in scripts:
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 \

**Comment by yaolug** [comment]
lora is supported, but we do not recommend using LoRA for finetuning. Performance is not as good as directly finetuning.

**Comment by Lyken17** [comment]
the lora args should be comptaible by default. But as @yaolug mentioned, we haven't measure the performance yet and acc degradtion is expected.

**Comment by hzhang57** [comment]
Thank you for confirmation

**Comment by HiHiAllen** [comment]
@hzhang57 Hi ,Have you fine-tuned successfully? I encountered the following error during training:
 `Traceback (most recent call last):
  File "/cfs-allenxmzhu/workspace/VILA/llava/train/train_mem.py", line 36, in <module>
    train()
  File "/cfs-allenxmzhu/workspace/VILA/llava/train/train.py", line 410, in train
    trainer.train()
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/transformers/trainer.py", line 1672, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/accelerate/accelerator.py", line 1198, in prepare
    result = self._prepare_deepspeed(*args)
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/accelerate/accelerator.py", line 1537, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/deepspeed/__init__.py", line 165, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 309, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1184, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1474, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer_Stage3(
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 300, in __init__
    self._setup_for_real_optimizer()
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 382, in _setup_for_real_optimizer
    self.initialize_optimizer_states()
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 892, in initialize_optimizer_states
    self._optimizer_step(i)
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 817, in _optimizer_step
    self.optimizer.step()
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/torch/optim/optimizer.py", line 373, in wrapper
    out = func(*args, **kwargs)
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/torch/optim/adamw.py", line 184, in step
    adamw(
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/torch/optim/adamw.py", line 335, in adamw
    func(
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/torch/optim/adamw.py", line 509, in _multi_tensor_adamw
    grouped_tensors = Optimizer._group_tensors_by_device_and_dtype([
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/torch/optim/optimizer.py", line 397, in _group_tensors_by_device_and_dtype
    return _group_tensors_by_device_and_dtype(tensorlistlist, with_indices)
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/vila/lib/python3.10/site-packages/torch/utils/_foreach_utils.py", line 42, in _group_tensors_by_device_and_dtype
    torch._C._group_tensors_by_device_and_dtype(tensorlistlist, with_indices).items()
RuntimeError: Tensors of the same index must be on the same device and the same dtype except `step` tensors that can be CPU and float32 notwithstanding`
