### ISSUE TITLE
ModuleNotFoundError: No module named 'llava.tf_utils'. Please help!

### ISSUE THREAD

**Issue by royshan** [NVlabs/VILA#23]
Hi,

Thank you for sharing the model!

When I tried to test the model with Colab, I ran into the error as follows. Please advise me to fix it. Thank you!

```
!bash environment_setup.sh
...

!python -W ignore llava/eval/run_vila.py \
    --model-path Efficient-Large-Model/Llama-3-VILA1.5-8b \
    --conv-mode llama_3 \
    --query "<image>\n Please describe the image." \
    --image-file 20231228.jpg

2024-06-19 08:01:22.103196: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-19 08:01:22.103250: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-19 08:01:22.236483: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-06-19 08:01:24.832522: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/VILA/llava/eval/run_vila.py", line 18, in <module>
    from llava.model.builder import load_pretrained_model
  File "/content/VILA/llava/model/__init__.py", line 1, in <module>
    from .language_model.llava_llama import LlavaLlamaModel, LlavaLlamaConfig
  File "/content/VILA/llava/model/language_model/llava_llama.py", line 34, in <module>
    from ..llava_arch import LlavaMetaModel, LlavaMetaForCausalLM
  File "/content/VILA/llava/model/llava_arch.py", line 49, in <module>
    from llava.model.multimodal_encoder.builder import build_vision_tower
  File "/content/VILA/llava/model/multimodal_encoder/builder.py", line 8, in <module>
    from .radio_encoder import RADIOVisionTower
  File "/content/VILA/llava/model/multimodal_encoder/radio_encoder.py", line 10, in <module>
    from .image_processor import ImageProcessor
  File "/content/VILA/llava/model/multimodal_encoder/image_processor.py", line 64, in <module>
    from ...tf_utils import flatten, shape_list
ModuleNotFoundError: No module named 'llava.tf_utils'
```

**Comment by Lyken17** [comment]
this is caused some tf dependencies, which should be deprectaed in our codeabse. Could you try to remove tensorflow or comment related snippets and run again?

**Comment by Lyken17** [comment]
Just crafted a PR to fix the issue 

https://github.com/NVlabs/VILA/pull/24

@yaolug please help merge

**Comment by Lyken17** [comment]
merged and the issue shall be fixed. Feel free to re-open if necessary.

**Comment by Lyken17** [comment]
Hi there,

Our team has moved our VILA to a new location: [NVLabs/VILA](https://github.com/NVlabs/VILA). We kindly request that you update your references to the old repository location with the new one (e.g, git clone / pipeline integration). This will ensure that you have access to the latest updates, improvements, and bug fixes for VILA project. Current repo will be archieved in one week (Jul 10th) and made private after one month (Aug 4th).

Thank you for your understanding and continued support. If your issue still exists, feel free to open a new one in the new place. We appreciate your patience and cooperation during this transition.

Best regards,
VILA Team
