### ISSUE TITLE
Can't run inference demo

### ISSUE THREAD

**Issue by zyddnys** [NVlabs/VILA#4]
Thank you for this wonderful work, however when i tried to run the inference demo i got `run_llava.py: error: unrecognized arguments: --model-name Efficient-Large-Model/VILA-13B`

so i changed `--model-name` to `--model-path`, but i got another error
```
[WARNING] the auto inferred conversation mode is llava_v0, while `--conv-mode` is vicuna_v1, using vicuna_v1
Traceback (most recent call last):
  File "/VILA/llava/eval/run_llava.py", line 159, in <module>
    eval_model(args)
  File "/VILA/llava/eval/run_llava.py", line 117, in eval_model
    output_ids = model.generate(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 1764, in generate
    return self.sample(
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 2861, in sample
    outputs = self(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/VILA/llava/model/language_model/llava_llama.py", line 86, in forward
    ) = self.prepare_inputs_labels_for_multimodal(
  File "/VILA/llava/model/llava_arch.py", line 202, in prepare_inputs_labels_for_multimodal
    cur_image_features = image_features[cur_image_idx]
IndexError: index 1 is out of bounds for dimension 0 with size 1
```

**Comment by ys-2020** [comment]
Hi. Thank you for your interest in VILA! The inference demo is hosted by [TinyChat](https://github.com/mit-han-lab/llm-awq/tree/main/tinychat) and [AWQ](https://github.com/mit-han-lab/llm-awq/tree/main). Please follow the instructions [here](https://github.com/mit-han-lab/llm-awq/tree/main/tinychat#usage) to prepare the model and launch the demo.

**Comment by wzw773828204** [comment]
python -W ignore llava/eval/run_llava.py \
    --model-path /root/autodl-tmp/VILA-7b \
    --conv-mode vicuna_v1 \
    --query "Please describe the traffic condition." \
    --image-file "demo_images/av.png"

改成这样就行了，他代码把prompt中已经加入<image>了，不需要再query中再加入<image>

**Comment by wzw773828204** [comment]
python -W ignore llava/eval/run_llava.py
--model-path /root/autodl-tmp/VILA-7b
--conv-mode vicuna_v1
--query "Please describe the traffic condition."
--image-file "demo_images/av.png"

改成这样就行了，他代码把prompt中已经加入了image，不需要在query中再加入image

**Comment by lobbyd** [comment]
Traceback (most recent call last):
  File "/home/hezl/code/VILA/llava/eval/run_llava.py", line 160, in <module>
    eval_model(args)
  File "/home/hezl/code/VILA/llava/eval/run_llava.py", line 118, in eval_model
    output_ids = model.generate(
  File "/home/hezl/anaconda3/envs/vila/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/hezl/anaconda3/envs/vila/lib/python3.10/site-packages/transformers/generation/utils.py", line 1764, in generate
    return self.sample(
  File "/home/hezl/anaconda3/envs/vila/lib/python3.10/site-packages/transformers/generation/utils.py", line 2897, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
When I run the interference command: 
python -W ignore llava/eval/run_llava.py \
    --model-path Efficient-Large-Model/VILA-13B \
    --conv-mode vicuna_v1 \
    --query "Please describe the traffic condition." \
    --image-file "demo_images/av.png"
    The error above happened, how I process it? @yaolug

**Comment by yaolug** [comment]
@lobbyd Sorry I cannot reproduce your issue. Could you provide more detail for us to reproduce?

**Comment by lobbyd** [comment]
@yaolug  Thank you, This question I have solved.  When I rewrite the code, the question disappear.

**Comment by Lyken17** [comment]
close as the issue has been resolved. Will update for a better inference interface next version.
