### ISSUE TITLE
fail to run the inference demo

### ISSUE THREAD

**Issue by heroacool** [NVlabs/VILA#8]
run the demo script, and get the following error. @yaolug  @Efficient-Large-Language-Model could you please help me?,

`python  llava/eval/run_vila.py     --model-path Efficient-Large-Model/Llama-3-VILA1.5-8b     --conv-mode llama_3     --query "<image>\n Please describe the traffic condition."     --image-file "demo_images/av.png"`

`Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Traceback (most recent call last):
  File "/media/md1/users/york/workspace/VILA/llava/eval/run_vila.py", line 162, in <module>
    eval_model(args)
  File "/media/md1/users/york/workspace/VILA/llava/eval/run_vila.py", line 124, in eval_model
    output_ids = model.generate(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/media/md1/users/york/workspace/VILA/llava/model/language_model/llava_llama.py", line 171, in generate
    outputs = self.llm.generate(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 1764, in generate
    return self.sample(
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 2924, in sample
    if stopping_criteria(input_ids, scores):
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/stopping_criteria.py", line 132, in __call__
    return any(criteria(input_ids, scores) for criteria in self)
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/stopping_criteria.py", line 132, in <genexpr>
    return any(criteria(input_ids, scores) for criteria in self)
  File "/media/md1/users/york/workspace/VILA/llava/mm_utils.py", line 298, in __call__
    outputs.append(self.call_for_batch(output_ids[i].unsqueeze(0), scores))
  File "/media/md1/users/york/workspace/VILA/llava/mm_utils.py", line 279, in call_for_batch
    raise ValueError(
ValueError: Keyword tensor should have 2 or 3 dimensions, got 1`

**Comment by kfzyqin** [comment]
I got the same error

**Comment by yaolug** [comment]
Sorry, there is an issue when moving the repo. I just fixed it. Could you try again?
Make sure you pass
`--conv-mode=hermes-2` for 40b
`--conv-mode=v1` for 13b
`--conv-mode=llama_3` for 8b
`--conv-mode=v1` for 3b

**Comment by kfzyqin** [comment]
Yes! it is working now! Thank you!

**Comment by heroacool** [comment]
git pull the code, and solved the problem. thanks!

**Comment by heroacool** [comment]
git pull the code, and solved the problem. thanks!

**Comment by Lyken17** [comment]
Hi there,

Our team has moved our VILA to a new location: [NVLabs/VILA](https://github.com/NVlabs/VILA). We kindly request that you update your references to the old repository location with the new one (e.g, git clone / pipeline integration). This will ensure that you have access to the latest updates, improvements, and bug fixes for VILA project. Current repo will be archieved in one week (Jul 10th) and made private after one month (Aug 4th).

Thank you for your understanding and continued support. If your issue still exists, feel free to open a new one in the new place. We appreciate your patience and cooperation during this transition.

Best regards,
VILA Team
